feat: select 페이지 생성
LikeLion-KNU/dongBTI pull request #11
Opened 2024-09-04 12:51 UTC by WithJo

## 구현한 기능

-

## 논의하고 싶은 내용

-

## 기타

-

2024-09-04 14:20 UTC, toothlessdev requested changes

2024-09-04 14:20 UTC, toothlessdev commented on src/Router.tsx
> +            </Route>
`/select` 에 대한 컴포넌트를 `RootLayout` 으로 한번 더 감싼 이유가 있을까요 ??

2024-09-04 14:20 UTC, toothlessdev commented on src/constants/Question.tsx
사용하지 않는 파일은 제거해주시면 좋을것 같습니다!

2024-09-04 14:20 UTC, toothlessdev commented on src/pages/SelectPage.tsx
> +                                        )
이부분을 컴포넌트 상단으로 빼고, switch 문을 사용해서 리턴해주면 좀 더 가독성이 올라갈 것 같습니다!

2024-09-05 01:29 UTC, WithJo commented on src/Router.tsx
> +            </Route>
없습니다. 수정했습니다.

2024-09-05 01:37 UTC, WithJo commented on src/pages/SelectPage.tsx
> +                                        )
추가했습니다.

2024-09-05 01:56 UTC, WithJo commented on src/constants/Question.tsx
사용하지 않는 Question.tsx파일 삭제했습니다.

2024-09-05 05:15 UTC, junyeokk commented
구현하시느라 고생 많으셨습니다. 전체적으로 커밋들을 세분화하신 부분은 잘 진행하신 것 같습니다.

다만 코드들이 조금 정돈되면 좋겠다는 느낌을 많이 받은 것 같아요. 아무래도 일관성을 지킨 코드는 나중에 유지보수도 쉽고 협업하기에도 더 수월할 것이기 때문에 그 부분만 조금만 조심해서 코드 작성하면 좋을 것 같습니다!

2024-09-05 05:18 UTC, junyeokk commented on src/pages/SelectPage.tsx
> +                                style={
style을 inline으로 넣지 않고 따로 분리해주면 더욱 좋을 것 같습니다. 가독성도 많이 안 좋아지고 다른 pages 파일들과 다르게 구현된 부분이 나중에 봤을 때 혼란이 올 수도 있어서 최대한 피하는게 좋습니다.

2024-09-05 05:24 UTC, junyeokk commented on src/pages/SelectPage.style.ts
> +    background-color: #37cdcd;
`styles/global.ts`에 전역으로 설정된 css variable 값이 있다면 그걸 사용하는게 유지보수 측면에서 편리할 거에요. 

재용님이 작성하신 background-color 말고도 전체적으로 css가 복잡한게 많이 느껴지는 것 같습니다.

:root를 활용해서 css variable로 표현할 수 있는 것은 최대한 표현하는 방향으로 개선해나가면 좋을 것 같네요. 서로 합의 하에 :root를 다시 수정해나가는 것도 괜찮아 보여요

2024-09-06 10:01 UTC, WithJo commented on src/pages/SelectPage.tsx
> +                                style={
variant를 변경하는 방식으로 수정했습니다.

2024-09-06 10:06 UTC, WithJo commented on src/pages/SelectPage.style.ts
> +    background-color: #37cdcd;
해당부분은 제 코드에서는 이미 삭제된 부분으로 파악됩니다. :root를 활용하자는 조언 감사합니다. 추후에 필요하다면 최대한 활용할 수 있도록 하겠습니다.

2024-09-06 14:55 UTC, toothlessdev approved these changes
LGTM!

2024-09-06 14:55 UTC, merged