Feature/main page 메인 페이지 수정
LikeLion-KNU/dongBTI pull request #13
Opened 2024-09-04 15:03 UTC by 2NNS-V

## 구현한 기능

- 메인 페이지에서 img 추가
- 드롭다운 컴포넌트 추가 및 적용
- 통계 페이지 퍼블리싱
- 전역 변수 설정
- 동아리 로고 Footer 컴포넌트 추가
- png -> svg 확장자명 변경

## 논의하고 싶은 내용

- 

## 기타

- 통계페이지 디자인은 아직 수정중

2024-09-04 15:22 UTC, toothlessdev requested changes

2024-09-04 15:22 UTC, toothlessdev commented on src/components/display/Footer.tsx
> +`;
이부분 `Footer.style.ts` 로 스타일 관련 코드를 분리하는게 좋아 보입니다!

2024-09-04 15:22 UTC, toothlessdev commented on src/components/form/Dropdown.tsx
> +export default function dropdown({ color, width, height, selectedMajor, setSelectedMajor }: DropdownProps) {
컴포넌트 이름은 CamelCase 로 작성해주세요!

2024-09-04 15:22 UTC, toothlessdev commented on src/components/form/Dropdown.tsx
> +export default function dropdown({ color, width, height, selectedMajor, setSelectedMajor }: DropdownProps) {
`export defualt` 로 내보냈기 때문에 `import DropDown from "@/components/form/DropDown"` 으로 참조 가능하지만, HTML 기본 DOM Element 와 구별하기 위해 React 공식문서에서도 CamelCase 로 작성하는것을 권장하고 있습니다

2024-09-04 15:22 UTC, toothlessdev commented on src/components/navigation/SideBar.tsx
> +  return (
path 매개변수에 analytics 이외의 값이 들어가지 않는 다면 다른 path 를 받지 않고 바로 `navigate("/analytics")` 와 같이 작성하는게 좋지 않을까요 ?
handleSideBar 또한 그냥 `setIsOpen(false)` 를 호출해도 상관 없을것 같아요!

예)
```tsx
const navigateToAnalytics = () => {
    navigate("/analytics");
    setIsOpen(false);
}

<Menu onClick={navigateToAnalytics}>
```

2024-09-04 15:36 UTC, 2NNS-V commented on src/components/navigation/SideBar.tsx
> +  return (
```
           <ul>
                <Menu>테스트</Menu>
                <Menu onClick={() => handleNavigation("/analytics")}>통계</Menu>
                <Menu>만든이들</Menu>
            </ul>
```
각 메뉴마다 이동할 때 `handleNavigation("/select")`, `handleNavigation("/makers")` 이런 식으로 세번 사용될 것 같아요!

2024-09-04 15:37 UTC, 2NNS-V commented on src/components/navigation/SideBar.tsx
> +  return (
handleNavigation 함수명을 직관적으로 바꾸는게 좋을까요?

2024-09-04 15:45 UTC, toothlessdev commented on src/components/navigation/SideBar.tsx
> +  return (
아 이해했습니다! 아직 테스트와 만든이들에 연결이 안되어있군요! 그대로 두셔도 괜찮을것 같아요!

2024-09-04 15:52 UTC, 2NNS-V commented on src/components/form/Dropdown.tsx
> +export default function dropdown({ color, width, height, selectedMajor, setSelectedMajor }: DropdownProps) {
`dropDown`이 camelCase로 알고 있는데, `DropDown`으로 써야 하나요?

2024-09-04 15:55 UTC, toothlessdev commented on src/components/form/Dropdown.tsx
> +export default function dropdown({ color, width, height, selectedMajor, setSelectedMajor }: DropdownProps) {
아 PascalCase 입니다! 헷갈렸네요;; `DropDown` 으로 변경해주시면 될것 같습니다!

2024-09-04 16:47 UTC, toothlessdev approved these changes
LGTM! any 는 최대한 피하고 명시적으로 타입을 지정하는 습관을 들이면 좋을것 같아요!

2024-09-05 03:26 UTC, toothlessdev approved these changes
LGTM!

2024-09-05 05:02 UTC, merged