feat: Text 굵기 선택 지원 + global.ts weight 추가
LikeLion-KNU/dongBTI pull request #5
Opened 2024-08-28 13:17 UTC by whitedev7773

## 구현한 기능
- `typograph/Text.tsx` weight props 추가
- ~~weight | "l" | "r" | "b" | "eb" | "h", weight가 주어지지 않으면 기본값은 r로 설정~~
- weight | "light" | "regular" | "bold" | "extrabold" | "heavy", weight가 주어지지 않으면 기본값은 regular로 설정

## 논의하고 싶은 내용
- X

## 기타
- light, regular, bold, extrabold, heavy

2024-08-28 13:25 UTC, toothlessdev approved these changes
LGTM!

2024-08-28 13:27 UTC, toothlessdev requested changes
weight 프로퍼티를 좀 더 직관적으로 알 수 있게 바꾸면 좋을것 같습니다!

2024-08-28 13:31 UTC, junyeokk commented
> weight 프로퍼티를 좀 더 직관적으로 알 수 있게 바꾸면 좋을것 같습니다!

tailwind 참고해보는 것도 좋아요

https://tailwindcss.com/docs/font-weight

2024-08-29 00:40 UTC, toothlessdev approved these changes
LGTM!

2024-08-29 00:42 UTC, merged